#!/usr/bin/env python3
"""
Measure the approved MUSE-UM exhibits so the 3D room can be matched to them
numerically instead of by eye.

For each exhibit it reports: canvas size, mean luminance, mean saturation,
mean edge density (a proxy for how much ink is in the frame), and the top
quantised colours with their share of the frame.

Run through the npm script, which supplies the interpreter and Pillow:

    npm run art:palette
    npm run art:palette -- --write      # also writes docs/measured-exhibit-palette.md

Exit code is 0 unless --assert is passed and the measurements fall outside the
recorded bands, which is how this becomes a regression check rather than a
report.
"""
from __future__ import annotations

import argparse
import glob
import os
import sys

from PIL import Image, ImageFilter, ImageStat

# Pillow moved these into enums; fall back for older versions.
RESAMPLE_LANCZOS = getattr(getattr(Image, "Resampling", Image), "LANCZOS")
QUANTIZE_MEDIANCUT = getattr(getattr(Image, "Quantize", Image), "MEDIANCUT")

ART_GLOB = "public/art/*.png"
# These are character references, not exhibits. Including them would drag the
# measured palette toward a single figure's colours.
EXCLUDE = ("canonical", "turnaround")

# Bands recorded from the approved exhibits on 2026-09-29. The 3D rooms are
# judged against these, so the bands themselves must not silently drift.
BANDS = {
    "luminance": (70.0, 115.0),
    "saturation": (55.0, 130.0),
    "edge_density": (24.0, 46.0),
}


def measure(path: str) -> dict:
    im = Image.open(path).convert("RGB")
    small = im.resize((160, 160), RESAMPLE_LANCZOS)

    grey = im.convert("L")
    luminance = ImageStat.Stat(grey).mean[0]
    edge_density = ImageStat.Stat(grey.filter(ImageFilter.FIND_EDGES)).mean[0]
    saturation = ImageStat.Stat(small.convert("HSV")).mean[1]

    quant = small.quantize(colors=8, method=QUANTIZE_MEDIANCUT).convert("RGB")
    total = 160 * 160
    counts = sorted(quant.getcolors(total) or [], reverse=True)
    top = [
        {"hex": "#%02x%02x%02x" % rgb, "share": round(n / total * 100, 1)}
        for n, rgb in counts[:8]
    ]

    return {
        "path": path,
        "name": os.path.basename(path),
        "size": im.size,
        "luminance": round(luminance, 1),
        "saturation": round(saturation, 1),
        "edge_density": round(edge_density, 1),
        "top": top,
    }


def exhibits() -> list[dict]:
    rows = []
    for path in sorted(glob.glob(ART_GLOB)):
        if any(token in os.path.basename(path) for token in EXCLUDE):
            continue
        rows.append(measure(path))
    if not rows:
        sys.exit(f"No exhibits found at {ART_GLOB}")
    return rows


def aggregate(rows: list[dict]) -> list[tuple[str, float]]:
    totals: dict[str, float] = {}
    for row in rows:
        for entry in row["top"]:
            totals[entry["hex"]] = totals.get(entry["hex"], 0.0) + entry["share"]
    n = len(rows)
    return sorted(((h, v / n) for h, v in totals.items()), key=lambda kv: -kv[1])


def report(rows: list[dict]) -> str:
    lines = []
    lines.append(
        f"{'file':26} {'canvas':12} {'lum':>6} {'sat':>6} {'edge':>6}  dominant"
    )
    for r in rows:
        size = f"{r['size'][0]}x{r['size'][1]}"
        top = ", ".join(f"{e['hex']} {e['share']}%" for e in r["top"][:5])
        lines.append(
            f"{r['name']:26} {size:12} {r['luminance']:6} {r['saturation']:6} "
            f"{r['edge_density']:6}  {top}"
        )
    lines.append("")
    lines.append("Aggregate dominant colours across the exhibit set:")
    for hexval, share in aggregate(rows)[:14]:
        lines.append(f"  {hexval}  {share:.1f}% mean share")
    return "\n".join(lines)


def band_check(rows: list[dict]) -> list[str]:
    failures = []
    for row in rows:
        for key, (low, high) in BANDS.items():
            value = row[key]
            if not (low <= value <= high):
                failures.append(
                    f"{row['name']}: {key} {value} outside recorded band {low}-{high}"
                )
    return failures


def write_markdown(rows: list[dict], path: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    out = [
        "# Measured exhibit palette — recorded baseline",
        "",
        "Generated by `npm run art:palette -- --write`. This file is a baseline, not a document to",
        "edit: if the numbers move, the exhibits moved and every 3D target derived from them has to be",
        "revisited.",
        "",
        f"Exhibits measured: **{len(rows)}**",
        "",
        "| exhibit | canvas | mean lum | mean sat | edge density | dominant tones |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        size = f"{r['size'][0]}×{r['size'][1]}"
        top = " ".join(f"`{e['hex']}`" for e in r["top"][:4])
        out.append(
            f"| {r['name'].replace('.png', '')} | {size} | {r['luminance']} | "
            f"{r['saturation']} | {r['edge_density']} | {top} |"
        )
    out += [
        "",
        "## Recorded bands",
        "",
        f"- mean luminance: **{BANDS['luminance'][0]}–{BANDS['luminance'][1]}**",
        f"- mean saturation: **{BANDS['saturation'][0]}–{BANDS['saturation'][1]}**",
        f"- mean edge density: **{BANDS['edge_density'][0]}–{BANDS['edge_density'][1]}**",
        "",
        "## Aggregate dominant colours",
        "",
    ]
    for hexval, share in aggregate(rows)[:16]:
        out.append(f"- `{hexval}` — {share:.1f}% mean share")
    out.append("")
    with open(path, "w") as handle:
        handle.write("\n".join(out))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="write the markdown baseline")
    parser.add_argument(
        "--assert",
        dest="do_assert",
        action="store_true",
        help="exit non-zero if any exhibit falls outside the recorded bands",
    )
    args = parser.parse_args()

    rows = exhibits()
    print(report(rows))

    if args.write:
        target = "docs/measured-exhibit-palette.md"
        write_markdown(rows, target)
        print(f"\nWrote {target}")

    if args.do_assert:
        failures = band_check(rows)
        if failures:
            print("\nBAND FAILURES:")
            for line in failures:
                print(f"  {line}")
            return 1
        print("\nAll exhibits inside the recorded bands.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
