#!/usr/bin/env bash
# Publish the built pavilion to the gh-pages branch that GitHub Pages serves at
# https://ousiaresearch.github.io/muse-um/
#
# The built site is never hand-edited: run this. It builds from the current main
# commit, stamps the served JSON with the source revision, and force-pushes the
# generated tree to gh-pages. Re-running is the normal way to change the site.
#
# Usage:  scripts/publish.sh
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_DIR"

if [ -n "$(git status --porcelain)" ]; then
  echo "refusing to publish: the working tree has uncommitted changes." >&2
  echo "commit them first so the published revision is a revision." >&2
  exit 1
fi

SOURCE_SHA="$(git rev-parse HEAD)"
BUILT_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
ORIGIN="$(git remote get-url origin)"

echo "building main@${SOURCE_SHA:0:12} at ${BUILT_AT}"
npm run build
python3 scripts/stamp.py "$BUILT_AT" "$SOURCE_SHA"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

git clone -q --depth 1 "$ORIGIN" "$WORK/pages"
cd "$WORK/pages"
git checkout -q --orphan gh-pages
git rm -r -q --cached . 2>/dev/null || true
find . -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
cp -R "$REPO_DIR/dist/." .
touch .nojekyll

{
  echo "Publish the built pavilion"
  echo
  echo "Generated by scripts/publish.sh from main@${SOURCE_SHA} at ${BUILT_AT}."
  echo "Served at https://ousiaresearch.github.io/muse-um/"
  echo
  echo "Nothing here is hand-edited. Change main and re-run scripts/publish.sh;"
  echo "this branch is replaced whole each time."
} > "$WORK/message.txt"

git add -A
git -c user.name="Isildur" \
    -c user.email="261687298+ousiaresearch@users.noreply.github.com" \
    commit -q -F "$WORK/message.txt"

echo "publishing $(git rev-parse --short HEAD) to gh-pages"
git push -qf origin gh-pages

echo "published. Pages rebuilds in under a minute; verify with:"
echo "  curl -sI https://ousiaresearch.github.io/muse-um/ | head -1"
