#!/usr/bin/env python3
"""
Capture and measure every room in the pavilion against the congruency contract.

This is the Phase 2 baseline: what all eight rooms actually measure before any
architectural work. It exists so that a later claim of improvement has something
to be an improvement ON — without a recorded baseline, "the rooms look better
now" is an opinion.

    npm run sweep                  # capture + measure all rooms
    npm run sweep -- --rooms observatory,fossil_wall
    npm run sweep -- --reuse       # measure captures already on disk

Captures land in artifacts/sweep/<room>.png (gitignored) and the table is written
to docs/room-gate-sweep.md, which IS committed: the numbers are the artifact.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
sys.path.insert(0, HERE)

from importlib import import_module

_measure = import_module("measure-capture")
from PIL import Image

MANIFEST = os.path.join(ROOT, "src", "pavilion.manifest.json")
TOKENS = os.path.join(ROOT, "src", "style.tokens.json")
OUT_DIR = os.path.join(ROOT, "artifacts", "sweep")
DOC = os.path.join(ROOT, "docs", "room-gate-sweep.md")
CANVAS = (360, 28, 1080, 748)


def room_ids() -> list[str]:
    with open(MANIFEST) as handle:
        manifest = json.load(handle)
    return [room["id"] for room in manifest["rooms"]]


def capture(room: str, out: str) -> bool:
    result = subprocess.run(
        ["node", "scripts/capture-cdp.mjs", room, out],
        cwd=ROOT,
        capture_output=True,
        text=True,
        timeout=600,
    )
    if result.returncode != 0:
        print(f"  capture FAILED for {room}: {result.stderr.strip()[:200]}", file=sys.stderr)
        return False
    line = next((l for l in result.stdout.splitlines() if l.startswith("captured")), "")
    print(f"  {line or 'captured ' + room}")
    return True


def verdict(value, low, high) -> str:
    return "PASS" if low <= value <= high else "FAIL"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rooms", help="comma-separated subset")
    parser.add_argument("--reuse", action="store_true", help="measure existing captures")
    args = parser.parse_args()

    with open(TOKENS) as handle:
        tokens = json.load(handle)
    palette, contract = tokens["palette"], tokens["contract"]

    rooms = args.rooms.split(",") if args.rooms else room_ids()
    os.makedirs(OUT_DIR, exist_ok=True)

    lum_band = contract["luminance"]
    sat_band = contract["saturation"]
    ink_band = contract["inkLineShare"]
    pal_floor = contract["paletteShare"]

    rows = []
    for room in rooms:
        out = os.path.join(OUT_DIR, f"{room}.png")
        print(f"== {room}")
        if args.reuse and os.path.exists(out):
            print(f"  reusing {out}")
        elif not capture(room, out):
            rows.append({"room": room, "error": "capture failed"})
            continue

        m = _measure.metrics(Image.open(out), CANVAS, palette)
        rows.append({"room": room, **m})

    lines = [
        "# Room gate sweep — Phase 2 baseline",
        "",
        f"Variant: **{tokens['stylization']['variant']}**  ·  rooms measured: **{len(rows)}**",
        "",
        "Generated by `npm run sweep`. Bands are the artwork's own measured values"
        " (see `docs/measured-exhibit-palette.md`), not targets chosen by hand.",
        "",
        "| room | luminance | saturation | palette | ink line | verdict |",
        "|---|---|---|---|---|---|",
    ]

    failures = 0
    for row in rows:
        if "error" in row:
            lines.append(f"| {row['room']} | — | — | — | — | {row['error']} |")
            failures += 1
            continue
        checks = [
            verdict(row["luminance"], *lum_band),
            verdict(row["saturation"], *sat_band),
            verdict(row["palette_share"], pal_floor, 1.0),
            verdict(row["ink_line_share"], *ink_band),
        ]
        bad = checks.count("FAIL")
        failures += bad
        summary = "all gates pass" if bad == 0 else f"{bad} gate(s) failing"
        lines.append(
            f"| {row['room']} | {row['luminance']:.1f} | {row['saturation']:.1f} "
            f"| {row['palette_share']:.1%} | {row['ink_line_share']:.1%} | {summary} |"
        )

    lines += [
        "",
        "## Bands",
        "",
        f"- luminance {lum_band[0]}–{lum_band[1]}",
        f"- saturation {sat_band[0]}–{sat_band[1]}",
        f"- palette share ≥ {pal_floor:.0%} (the exhibits' own mean)",
        f"- ink-line share {ink_band[0]:.0%}–{ink_band[1]:.0%} (exhibit range 12.5–24.5%)",
        "",
        f"**Failing gates across the sweep: {failures}.** "
        "Ink-line is expected to fail everywhere at this stage: the rooms are bare"
        " planes with three inked objects each, and Phase 2 gives them architecture"
        " to draw.",
        "",
    ]

    with open(DOC, "w") as handle:
        handle.write("\n".join(lines))

    print()
    print("\n".join(lines[4:]))
    print(f"\nwrote {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
