#!/usr/bin/env python3
"""
Capture and measure every room in the pavilion against the congruency contract.

This is the Phase 2 baseline: what all eight rooms actually measure before any
architectural work. It exists so that a later claim of improvement has something
to be an improvement ON — without a recorded baseline, "the rooms look better
now" is an opinion.

    npm run sweep                  # capture + measure all rooms
    npm run sweep -- --rooms observatory,fossil_wall
    npm run sweep -- --reuse       # measure captures already on disk

Captures land in artifacts/sweep/<room>.png (gitignored) and the table is written
to docs/room-gate-sweep.md, which IS committed: the numbers are the artifact.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
sys.path.insert(0, HERE)

from importlib import import_module

_measure = import_module("measure-capture")
from PIL import Image

MANIFEST = os.path.join(ROOT, "src", "pavilion.manifest.json")
TOKENS = os.path.join(ROOT, "src", "style.tokens.json")
OUT_DIR = os.path.join(ROOT, "artifacts", "sweep")
DOC = os.path.join(ROOT, "docs", "room-gate-sweep.md")

# The capture harness now clips the screenshot to the WebGL canvas, so the canvas IS
# the whole image and the measured region must be derived from the file. This was
# previously a hardcoded page-relative box (360, 28, 1080, 748) from when captures
# were full-page 1440x900 screenshots. Once captures became 720x720 canvas crops,
# that box ran 360px off the right edge, PIL filled the overhang with black, and the
# sweep duly reported every room as far darker than it is — luminance 46 against a
# true 75. A stale measurement region is indistinguishable from a real regression
# until you compare the number against a differently-derived one.
def canvas_region(image) -> tuple[int, int, int, int]:
    return (0, 0, image.size[0], image.size[1])


def room_ids() -> list[str]:
    with open(MANIFEST) as handle:
        manifest = json.load(handle)
    return [room["id"] for room in manifest["rooms"]]


def capture(room: str, out: str, attempts: int = 3) -> bool:
    """Capture a room, retrying transient failures.

    A capture failure is indistinguishable from a real problem in the report, and the
    harness spawns its own Chrome per room — so contention from anything else running
    on the machine surfaces as a room silently missing its row. Observed once for real
    when four generators were running at the same time.
    """
    for attempt in range(1, attempts + 1):
        result = subprocess.run(
            ["node", "scripts/capture-cdp.mjs", room, out],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=600,
        )
        if result.returncode == 0:
            line = next((l for l in result.stdout.splitlines() if l.startswith("captured")), "")
            print(f"  {line or 'captured ' + room}" + (f"  (attempt {attempt})" if attempt > 1 else ""))
            return True
        detail = result.stderr.strip().splitlines()[-1][:160] if result.stderr.strip() else "no stderr"
        if attempt < attempts:
            print(f"  attempt {attempt} failed for {room} ({detail}); retrying", file=sys.stderr)
            time.sleep(3)
        else:
            print(f"  capture FAILED for {room} after {attempts} attempts: {detail}", file=sys.stderr)
    return False


def verdict(value, low, high) -> str:
    return "PASS" if low <= value <= high else "FAIL"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rooms", help="comma-separated subset")
    parser.add_argument("--reuse", action="store_true", help="measure existing captures")
    args = parser.parse_args()

    with open(TOKENS) as handle:
        tokens = json.load(handle)
    palette, contract = tokens["palette"], tokens["contract"]

    rooms = args.rooms.split(",") if args.rooms else room_ids()
    os.makedirs(OUT_DIR, exist_ok=True)

    lum_band = contract["luminance"]
    sat_band = contract["saturation"]
    ink_band = contract["inkLineShare"]
    pal_floor = contract["paletteShare"]

    rows = []
    for room in rooms:
        out = os.path.join(OUT_DIR, f"{room}.png")
        print(f"== {room}")
        if args.reuse and os.path.exists(out):
            print(f"  reusing {out}")
        elif not capture(room, out):
            rows.append({"room": room, "error": "capture failed"})
            continue

        image = Image.open(out)
        m = _measure.metrics(image, canvas_region(image), palette)
        rows.append({"room": room, **m})

    lines = [
        "# Room gate sweep — Phase 2 baseline",
        "",
        f"Variant: **{tokens['stylization']['variant']}**  ·  rooms measured: **{len(rows)}**",
        "",
        "Generated by `npm run sweep`. Bands are the artwork's own measured values"
        " (see `docs/measured-exhibit-palette.md`), not targets chosen by hand.",
        "",
        "| room | luminance | saturation | palette | ink line | verdict |",
        "|---|---|---|---|---|---|",
    ]

    failures = 0
    for row in rows:
        if "error" in row:
            lines.append(f"| {row['room']} | — | — | — | — | {row['error']} |")
            failures += 1
            continue
        checks = [
            verdict(row["luminance"], *lum_band),
            verdict(row["saturation"], *sat_band),
            verdict(row["palette_share"], pal_floor, 1.0),
            verdict(row["ink_line_share"], *ink_band),
        ]
        bad = checks.count("FAIL")
        failures += bad
        summary = "all gates pass" if bad == 0 else f"{bad} gate(s) failing"
        lines.append(
            f"| {row['room']} | {row['luminance']:.1f} | {row['saturation']:.1f} "
            f"| {row['palette_share']:.1%} | {row['ink_line_share']:.1%} | {summary} |"
        )

    lines += [
        "",
        "## Bands",
        "",
        f"- luminance {lum_band[0]}–{lum_band[1]}",
        f"- saturation {sat_band[0]}–{sat_band[1]}",
        f"- palette share ≥ {pal_floor:.0%} (the exhibits' own mean)",
        f"- ink-line share {ink_band[0]:.0%}–{ink_band[1]:.0%} (exhibit range 12.5–24.5%)",
        "",
        f"**Failing gates across the sweep: {failures}.** "
        "Ink-line is the one gate that fails in every room, and the kit did not"
        " move it: the props are furniture standing on a floor, and a room with"
        " one decorated face has almost no inked geometry for the measure to"
        " find. More objects will not close it. Surfaces will — side walls, a"
        " ceiling, openings — which is the next wave, not this one.",
        "",
    ]

    with open(DOC, "w") as handle:
        handle.write("\n".join(lines))

    print()
    print("\n".join(lines[4:]))
    print(f"\nwrote {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
